import { fonts } from './fonts'

export const typography = {
  fontFamily: fonts.body,
  h1: {
    fontFamily: fonts.heading,
    fontWeight: 750,
    fontSize: '3.5rem',
    lineHeight: 1.1,
    letterSpacing: '0',
  },
  h2: {
    fontFamily: fonts.heading,
    fontWeight: 750,
    fontSize: '2.625rem',
    lineHeight: 1.15,
    letterSpacing: '0',
  },
  h3: {
    fontFamily: fonts.heading,
    fontWeight: 700,
    fontSize: '2.125rem',
    lineHeight: 1.22,
  },
  h4: {
    fontFamily: fonts.heading,
    fontWeight: 700,
    fontSize: '1.75rem',
    lineHeight: 1.28,
  },
  h5: {
    fontFamily: fonts.heading,
    fontWeight: 650,
    fontSize: '1.45rem',
    lineHeight: 1.34,
  },
  h6: {
    fontFamily: fonts.heading,
    fontWeight: 650,
    fontSize: '1.2rem',
    lineHeight: 1.4,
  },
  subtitle1: { fontWeight: 600, fontSize: '1.125rem', lineHeight: 1.5 },
  subtitle2: { fontWeight: 600, fontSize: '1rem', lineHeight: 1.5 },
  body1: { fontSize: '1.0625rem', lineHeight: 1.65 },
  body2: { fontSize: '0.975rem', lineHeight: 1.55 },
  caption: { fontSize: '0.85rem', lineHeight: 1.45 },
  overline: {
    fontWeight: 750,
    fontSize: '0.8rem',
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
  },
  button: {
    fontWeight: 700,
    fontSize: '0.975rem',
    textTransform: 'none' as const,
  },
  code: {
    fontFamily: fonts.mono,
    fontSize: '0.95rem',
    backgroundColor: 'rgba(0,0,0,0.06)',
    padding: '2px 6px',
    borderRadius: 10,
  },
  kbd: {
    fontFamily: fonts.mono,
    fontSize: '0.85rem',
    fontWeight: 650,
    padding: '2px 8px',
    borderRadius: 999,
    border: '1px solid',
  },
  label: { fontSize: '0.95rem', fontWeight: 650, lineHeight: 1.5 },
}
