/**
 * HTML Report Footer Module
 * Generates footer with metadata, timing information, and resources
 */
import { formatDuration } from '../../utils/formatters.js';
import { TOOL_METADATA } from '../../utils/constants.js';
export { generateResourcesSection, generateLegendSection, } from './HtmlFooterSections.js';
export function generateFooter(analysisTime, toolVersion) {
    const formattedTime = formatDuration(analysisTime);
    return (`<footer class="footer">\n` +
        `  <p>Analysis completed in ${formattedTime} | ` +
        `Tool v${toolVersion}</p>\n` +
        `  <div class="footer-meta">\n` +
        `    <small>This report was generated by Quality Validator` +
        `</small>\n  </div>\n</footer>`);
}
export function generateMetadataSection(timestamp, projectPath, nodeVersion) {
    const formattedDate = new Date(timestamp).toLocaleString();
    return (`<section class="section">\n  <h2>Report Metadata</h2>\n` +
        `  <div class="metrics-grid">\n` +
        `    <div class="metric">\n` +
        `      <div class="metric-label">Generated</div>\n` +
        `      <div class="metric-value">${formattedDate}</div>\n` +
        `    </div>\n` +
        `    <div class="metric">\n` +
        `      <div class="metric-label">Project Path</div>\n` +
        `      <div class="metric-value"><code>${projectPath}` +
        `</code></div>\n    </div>\n` +
        `    <div class="metric">\n` +
        `      <div class="metric-label">Node Version</div>\n` +
        `      <div class="metric-value"><code>${nodeVersion}` +
        `</code></div>\n    </div>\n` +
        `    <div class="metric">\n` +
        `      <div class="metric-label">Tool Version</div>\n` +
        `      <div class="metric-value">v${TOOL_METADATA.VERSION}` +
        `</div>\n    </div>\n  </div>\n</section>`);
}
export function generateScript() {
    return `
// Report initialization
document.addEventListener('DOMContentLoaded', function() {
  console.log('Quality Validation Report loaded');

  if (window.print) {
    const printStyle = document.createElement('style');
    printStyle.textContent =
      '@media print { .header { page-break-after: avoid; } ' +
      '.section { page-break-inside: avoid; } }';
    document.head.appendChild(printStyle);
  }

  const groups = document.querySelectorAll('.findings-group');
  groups.forEach(group => {
    const title = group.querySelector('h3');
    if (title) {
      title.style.cursor = 'pointer';
      title.addEventListener('click', function() {
        const items = group.querySelectorAll('.finding');
        items.forEach(item => {
          item.style.display =
            item.style.display === 'none' ? 'block' : 'none';
        });
      });
    }
  });
});
  `;
}
