export { isError } from './is-error'
export { isErrorLike } from './is-error-like'
export { isJsonValue } from './is-json-value'
export { getErrorMessage } from './get-error-message'
export { hasProperty } from './has-property'
