var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/_not-found/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__3a9a97c9._.js")
R.c("server/chunks/ssr/frontends_dockerterminal_frontend_98a1ced8._.js")
R.c("server/chunks/ssr/7851d_next_dist_esm_build_templates_app-page_054ad381.js")
R.c("server/chunks/ssr/[root-of-the-server]__63a9121e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__91d9c139._.js")
R.c("server/chunks/ssr/_6489d8a7._.js")
R.c("server/chunks/ssr/frontends_dockerterminal_frontend_app_555d16b2._.js")
R.c("server/chunks/ssr/frontends_dockerterminal_frontend_a865885c._.js")
R.c("server/chunks/ssr/7851d_next_dist_client_components_5c7fc595._.js")
R.c("server/chunks/ssr/7851d_next_dist_client_components_builtin_forbidden_7bdb795f.js")
R.c("server/chunks/ssr/c22a5_frontend__next-internal_server_app__not-found_page_actions_13f8257e.js")
R.m(28188)
module.exports=R.m(28188).exports
