// Icon system for fakemui
// Add icons as needed to reduce dependencies

export { Icon } from './Icon'
export type { IconProps } from './Icon'

// Actions
export { Plus } from './Plus'
export { Trash } from './Trash'
export { Copy } from './Copy'
export { Check } from './Check'
export { X } from './X'
export { Play } from './Play'
export { Pause } from './Pause'
export { Stop } from './Stop'
export { Download } from './Download'
export { Upload } from './Upload'
export { Filter } from './Filter'
export { Refresh } from './Refresh'

// Navigation
export { ArrowUp } from './ArrowUp'
export { ArrowDown } from './ArrowDown'
export { ArrowLeft } from './ArrowLeft'
export { ArrowRight } from './ArrowRight'
export { ArrowClockwise } from './ArrowClockwise'
export { ArrowCounterClockwise } from './ArrowCounterClockwise'
export { ArrowsClockwise } from './ArrowsClockwise'
export { ArrowsLeftRight } from './ArrowsLeftRight'
export { ArrowsOut } from './ArrowsOut'
export { ArrowsOutCardinal } from './ArrowsOutCardinal'
export { ArrowSquareIn } from './ArrowSquareIn'
export { ChevronUp } from './ChevronUp'
export { ChevronDown } from './ChevronDown'
export { ChevronLeft } from './ChevronLeft'
export { ChevronRight } from './ChevronRight'
export { CaretDown } from './CaretDown'
export { CaretRight } from './CaretRight'
export { Home } from './Home'
export { House } from './House'
export { ExternalLink } from './ExternalLink'
export { SignIn } from './SignIn'
export { SignOut } from './SignOut'

// Files & UI
export { FloppyDisk } from './FloppyDisk'
export { Search } from './Search'
export { MagnifyingGlass } from './MagnifyingGlass'
export { Settings } from './Settings'
export { Gear } from './Gear'
export { GearSix } from './GearSix'
export { User } from './User'
export { UserCircle } from './UserCircle'
export { UserPlus } from './UserPlus'
export { Users } from './Users'
export { UserSwitch } from './UserSwitch'
export { Menu } from './Menu'
export { Eye } from './Eye'
export { EyeSlash } from './EyeSlash'
export { Pencil } from './Pencil'
export { PencilSimple } from './PencilSimple'
export { Folder } from './Folder'
export { Code } from './Code'
export { Link } from './Link'
export { File } from './File'
export { FileText } from './FileText'
export { FileCode } from './FileCode'
export { FileArrowUp } from './FileArrowUp'
export { FileArrowDown } from './FileArrowDown'
export { Grid } from './Grid'
export { SquaresFour } from './SquaresFour'
export { List } from './List'
export { ListDashes } from './ListDashes'
export { ListNumbers } from './ListNumbers'
export { Image } from './Image'
export { Layout } from './Layout'
export { Table } from './Table'
export { Cursor } from './Cursor'
export { PaintBrush } from './PaintBrush'
export { Palette } from './Palette'

// Media & Display
export { Maximize } from './Maximize'
export { Minimize } from './Minimize'
export { Volume } from './Volume'
export { VolumeOff } from './VolumeOff'
export { Camera } from './Camera'
export { Video } from './Video'
export { Screen } from './Screen'
export { Broadcast } from './Broadcast'

// Communication & Time
export { Calendar } from './Calendar'
export { Clock } from './Clock'
export { Mail } from './Mail'
export { Envelope } from './Envelope'
export { EnvelopeSimple } from './EnvelopeSimple'
export { Bell } from './Bell'
export { ChatCircle } from './ChatCircle'
export { PaperPlaneTilt } from './PaperPlaneTilt'

// Data & Status
export { Database } from './Database'
export { HardDrives } from './HardDrives'
export { Info } from './Info'
export { Warning } from './Warning'
export { WarningCircle } from './WarningCircle'
export { CircleCheck } from './CircleCheck'
export { CheckCircle } from './CheckCircle'
export { CircleX } from './CircleX'
export { XCircle } from './XCircle'
export { Lightning } from './Lightning'
export { AlertCircle } from './AlertCircle'
export { AlertTriangle } from './AlertTriangle'
export { ChartLine } from './ChartLine'
export { TrendUp } from './TrendUp'
export { ShieldCheck } from './ShieldCheck'
export { ShieldWarning } from './ShieldWarning'
export { Lock } from './Lock'
export { LockKey } from './LockKey'
export { Power } from './Power'
export { Crown } from './Crown'
export { Sparkle } from './Sparkle'

// Social & Communication
export { Star } from './Star'
export { Heart } from './Heart'
export { Share } from './Share'
export { Smile } from './Smile'
export { Inbox } from './Inbox'
export { Edit } from './Edit'
export { Chat } from './Chat'
export { Send } from './Send'

// Security & Network
export { LockOpen } from './LockOpen'
export { Key } from './Key'
export { Shield } from './Shield'
export { Globe } from './Globe'
export { Cloud } from './Cloud'

// Developer & Tools
export { Terminal } from './Terminal'
export { Archive } from './Archive'
export { Bug } from './Bug'
export { Gavel } from './Gavel'
export { Clipboard } from './Clipboard'
export { Package } from './Package'
export { Layers } from './Layers'
export { Tag } from './Tag'
export { Bookmark } from './Bookmark'
export { BookOpen } from './BookOpen'
export { Tree } from './Tree'
export { Broom } from './Broom'
export { Export } from './Export'
export { UploadSimple } from './UploadSimple'
export { Funnel } from './Funnel'
export { FunnelSimple } from './FunnelSimple'
export { MapTrifold } from './MapTrifold'
export { PushPinSimple } from './PushPinSimple'
export { Buildings } from './Buildings'
export { GithubLogo } from './GithubLogo'
export { GoogleLogo } from './GoogleLogo'

// Theme & Display
export { Moon } from './Moon'
export { Sun } from './Sun'
export { Zap } from './Zap'
export { Expand } from './Expand'
export { Collapse } from './Collapse'
export { ZoomIn } from './ZoomIn'
export { ZoomOut } from './ZoomOut'

// UI Controls
export { MoreHorizontal } from './MoreHorizontal'
export { MoreVertical } from './MoreVertical'
export { Grip } from './Grip'
export { Pin } from './Pin'
export { Loader } from './Loader'
export { Save } from './Save'
export { Undo } from './Undo'
export { Redo } from './Redo'

// Data Table
export { SortAscending } from './SortAscending'
export { SortDescending } from './SortDescending'
export { ColumnResize } from './ColumnResize'
export { RowSelect } from './RowSelect'
export { SelectAll } from './SelectAll'
export { TableCells } from './TableCells'
export { Csv } from './Csv'
export { Json } from './Json'
export { FilterClear } from './FilterClear'
export { Columns } from './Columns'
export { Rows } from './Rows'
export { Pagination } from './Pagination'

// Layout & Navigation
export { Tab } from './Tab'
export { Tabs } from './Tabs'
export { Sidebar } from './Sidebar'
export { Toolbar } from './Toolbar'
export { Panel } from './Panel'

// Application Concepts
export { Transfer } from './Transfer'
export { Tenant } from './Tenant'
export { Tenants } from './Tenants'
export { Schema } from './Schema'
export { Workflow } from './Workflow'
export { Script } from './Script'
export { Supergod } from './Supergod'
export { History } from './History'
export { System } from './System'
export { Metrics } from './Metrics'

// Additional MUI-compatible Icons
export { GitBranch } from './GitBranch'
export { Robot } from './Robot'
export { FirstPage } from './FirstPage'
export { LastPage } from './LastPage'
export { Science } from './Science'
export { AutoAwesome } from './AutoAwesome'
export { CloudDownload } from './CloudDownload'
export { CloudUpload } from './CloudUpload'
export { CallSplit } from './CallSplit'
export { NavigateNext } from './NavigateNext'
export { FolderOpen } from './FolderOpen'
export { Description } from './Description'
export { ExpandMore } from './ExpandMore'
export { ExpandLess } from './ExpandLess'
export { Close } from './Close'
export { ErrorOutline } from './ErrorOutline'
export { InfoOutlined } from './InfoOutlined'
export { WarningAmber } from './WarningAmber'
export { Visibility } from './Visibility'
export { VisibilityOff } from './VisibilityOff'
export { Email } from './Email'
export { KeyboardArrowDown } from './KeyboardArrowDown'
export { Clear } from './Clear'
export { FilterList } from './FilterList'
export { LibraryAdd } from './LibraryAdd'
export { DeleteOutline } from './DeleteOutline'
export { DescriptionOutlined } from './DescriptionOutlined'
export { FolderOutlined } from './FolderOutlined'
export { FolderOpenOutlined } from './FolderOpenOutlined'
export { PlayArrow } from './PlayArrow'
export { MoreHoriz } from './MoreHoriz'
export { LockRounded } from './LockRounded'
export { CheckCircleOutline } from './CheckCircleOutline'
export { Cancel } from './Cancel'
export { HighlightOff } from './HighlightOff'
export { OpenInNew } from './OpenInNew'
export { Autorenew } from './Autorenew'

// Authentication & Access Control
export { Profile } from './Profile'
export { Login } from './Login'
export { Logout } from './Logout'
export { Register } from './Register'
export { Validate } from './Validate'
export { Gate } from './Gate'
export { Navigate } from './Navigate'
export { Stats } from './Stats'
export { Form } from './Form'
export { Level } from './Level'
export { Denied } from './Denied'
export { Redirect } from './Redirect'

// Drag & Drop
export { DragIndicator } from './DragIndicator'
export { DragHandle } from './DragHandle'

// Additional Actions
export { Print } from './Print'
export { Schedule } from './Schedule'
export { Tune } from './Tune'
export { ThumbUp } from './ThumbUp'
export { ThumbDown } from './ThumbDown'
export { Notifications } from './Notifications'
export { NotificationsOff } from './NotificationsOff'
export { ContentCopy } from './ContentCopy'
export { ContentPaste } from './ContentPaste'

// Component Icon Map
export { Article } from './Article'
export { Checkbox } from './Checkbox'
export { CropFree } from './CropFree'
export { CropPortrait } from './CropPortrait'
export { GridView } from './GridView'
export { LocalOffer } from './LocalOffer'
export { LooksOne } from './LooksOne'
export { Minus } from './Minus'
export { TableChart } from './TableChart'
export { TextFields } from './TextFields'
export { ToggleOn } from './ToggleOn'
export { TouchApp } from './TouchApp'
export { Verified } from './Verified'
export { ViewColumn } from './ViewColumn'
export { ViewStream } from './ViewStream'
export { AccountCircle } from './AccountCircle'
export { FormatAlignLeft } from './FormatAlignLeft'

// Media Center Icons
export { FilmSlate } from './FilmSlate'
export { Queue } from './Queue'
export { Tv } from './Tv'
export { Transform } from './Transform'
export { PictureAsPdf } from './PictureAsPdf'
export { Article } from './Article'
export { MenuBook } from './MenuBook'
export { SportsEsports } from './SportsEsports'
export { CameraAlt } from './CameraAlt'
export { FastForward } from './FastForward'
export { FastRewind } from './FastRewind'
export { Fullscreen } from './Fullscreen'
export { FullscreenExit } from './FullscreenExit'
export { People } from './People'
export { ArrowUpDown } from './ArrowUpDown'
export { SkipPrevious } from './SkipPrevious'
export { SkipNext } from './SkipNext'
export { Shuffle } from './Shuffle'
export { Repeat } from './Repeat'
export { RepeatOne } from './RepeatOne'
export { Gamepad } from './Gamepad'
export { Joystick } from './Joystick'
export { Radio } from './Radio'
export { Headphones } from './Headphones'
export { Mic } from './Mic'
export { MicOff } from './MicOff'
export { Subtitles } from './Subtitles'
export { ClosedCaption } from './ClosedCaption'
export { HighQuality } from './HighQuality'
export { AspectRatio } from './AspectRatio'
export { Speed } from './Speed'
export { Timer } from './Timer'

// Backup & Recovery
export { Backup } from './Backup'
export { Restore } from './Restore'
export { Storage } from './Storage'

// Admin & Management
export { AdminPanelSettings } from './AdminPanelSettings'
export { ManageAccounts } from './ManageAccounts'
export { AccountTree } from './AccountTree'
export { Domain } from './Domain'

// Security & Verification
export { SecurityUpdate } from './SecurityUpdate'
export { VpnKey } from './VpnKey'
export { VerifiedUser } from './VerifiedUser'
export { Policy } from './Policy'

// Help & Support
export { Help } from './Help'
