'use client';

import { useEffect, useState } from 'react';
import {
  Button, Checkbox, Dialog, DialogActions, DialogContent,
  DialogTitle, FormControlLabel, TextField,
} from '@metabuilder/components/fakemui';
import type { TdvColumn, TdvSchema } from './hooks/useTableDataView';

const NUM_TYPES = new Set([
  'integer', 'bigint', 'smallint', 'numeric', 'real',
  'double precision', 'decimal',
]);

function isAutoGenerated(col: TdvColumn, pks: string[]): boolean {
  if (!pks.includes(col.column_name)) return false;
  const def = col.column_default ?? '';
  return def.startsWith('nextval(') || def.includes('gen_random_uuid');
}

type Props = {
  open: boolean;
  mode: 'add' | 'edit';
  schema: TdvSchema;
  editingRow: any;
  onSubmit: (data: Record<string, any>) => Promise<void>;
  onClose: () => void;
};

export default function RowFormDialog({
  open, mode, schema, editingRow, onSubmit, onClose,
}: Props) {
  const [form, setForm] = useState<Record<string, any>>({});
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    if (!open) return;
    const init: Record<string, any> = {};
    schema.columns.forEach(col => {
      init[col.column_name] = editingRow?.[col.column_name] ?? '';
    });
    setForm(init);
  }, [open, schema, editingRow]);

  const handleSubmit = async () => {
    setSaving(true);
    try { await onSubmit(form); } catch { /* error shown in parent */ }
    finally { setSaving(false); }
  };

  const editableCols = schema.columns.filter(col =>
    mode === 'add' ? !isAutoGenerated(col, schema.primaryKeys) : true,
  );

  return (
    <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth>
      <DialogTitle>{mode === 'add' ? 'Add Row' : 'Edit Row'}</DialogTitle>
      <DialogContent>
        {editableCols.map(col => {
          const isPK = schema.primaryKeys.includes(col.column_name);
          const readonly = mode === 'edit' && isPK;
          if (col.data_type === 'boolean') {
            return (
              <FormControlLabel
                key={col.column_name}
                label={col.column_name}
                control={
                  <Checkbox
                    checked={!!form[col.column_name]}
                    disabled={readonly}
                    onChange={e =>
                      setForm(f => ({ ...f, [col.column_name]: e.target.checked }))
                    }
                  />
                }
                sx={{ display: 'block', mb: 1 }}
              />
            );
          }
          return (
            <TextField
              key={col.column_name}
              label={col.column_name + (isPK ? ' (PK)' : '')}
              value={form[col.column_name] ?? ''}
              onChange={e =>
                setForm(f => ({ ...f, [col.column_name]: e.target.value }))
              }
              type={NUM_TYPES.has(col.data_type) ? 'number' : 'text'}
              disabled={readonly}
              size="small"
              fullWidth
              sx={{ mb: 1.5 }}
            />
          );
        })}
      </DialogContent>
      <DialogActions>
        <Button onClick={onClose} disabled={saving}>Cancel</Button>
        <Button variant="contained" onClick={handleSubmit} disabled={saving}>
          {saving ? 'Saving…' : 'Save'}
        </Button>
      </DialogActions>
    </Dialog>
  );
}
