/** The pages a fresh instance starts with. */

export const SEED_PAGE_CONFIGS = [
  {
    path: '/',
    title: 'MetaBuilder',
    description: 'Data-driven application platform',
    packageId: 'ui_home',
    component: 'home_page',
    level: 0,
    requiresAuth: false,
    isPublished: true,
    sortOrder: 0,
  },
  {
    path: '/dashboard',
    title: 'Dashboard',
    packageId: 'dashboard',
    component: 'dashboard_home',
    level: 1,
    requiresAuth: true,
    isPublished: true,
    sortOrder: 0,
  },
  {
    path: '/profile',
    title: 'User Profile',
    packageId: 'dashboard',
    component: 'user_profile',
    level: 1,
    requiresAuth: true,
    isPublished: true,
    sortOrder: 50,
  },
  {
    path: '/login',
    title: 'Login',
    packageId: 'ui_login',
    component: 'login_page',
    level: 0,
    requiresAuth: false,
    isPublished: true,
    sortOrder: 0,
  },
  {
    path: '/admin',
    title: 'Administration',
    packageId: 'admin_dialog',
    component: 'admin_panel',
    level: 4,
    requiresAuth: true,
    isPublished: true,
    sortOrder: 0,
  },
  {
    path: '/admin/users',
    title: 'User Management',
    packageId: 'user_manager',
    component: 'user_list',
    level: 4,
    requiresAuth: true,
    isPublished: true,
    sortOrder: 10,
  },
  {
    path: '/admin/roles',
    title: 'Role Editor',
    packageId: 'role_editor',
    component: 'role_editor',
    level: 4,
    requiresAuth: true,
    isPublished: true,
    sortOrder: 20,
  },
  {
    path: '/admin/database',
    title: 'Database Manager',
    packageId: 'database_manager',
    component: 'database_manager',
    level: 5,
    requiresAuth: true,
    isPublished: true,
    sortOrder: 30,
  },
  {
    path: '/admin/schema',
    title: 'Schema Editor',
    packageId: 'schema_editor',
    component: 'schema_editor',
    level: 5,
    requiresAuth: true,
    isPublished: true,
    sortOrder: 40,
  },
  {
    path: '/admin/packages',
    title: 'Package Manager',
    packageId: 'package_manager',
    component: 'package_list',
    level: 4,
    requiresAuth: true,
    isPublished: true,
    sortOrder: 50,
  },
]
