/**
 * Every failure the workflow API can report.
 *
 * Split out of workflow-error-handler.ts so the codes and the three tables
 * keyed by them can be checked against each other -- a code missing from a
 * table ships `undefined` as an HTTP status.
 */

export enum WorkflowErrorCode {
  // Validation errors (400)
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  INVALID_NODE_TYPE = 'INVALID_NODE_TYPE',
  INVALID_CONNECTION = 'INVALID_CONNECTION',
  INVALID_WORKFLOW_STRUCTURE = 'INVALID_WORKFLOW_STRUCTURE',
  DUPLICATE_NODE_NAME = 'DUPLICATE_NODE_NAME',
  CIRCULAR_DEPENDENCY = 'CIRCULAR_DEPENDENCY',
  TYPE_MISMATCH = 'TYPE_MISMATCH',
  INVALID_TENANT_ID = 'INVALID_TENANT_ID',
  MISSING_TENANT_ID = 'MISSING_TENANT_ID',

  // Execution errors (500)
  EXECUTION_ERROR = 'EXECUTION_ERROR',
  EXECUTION_FAILED = 'EXECUTION_FAILED',
  NODE_EXECUTION_FAILED = 'NODE_EXECUTION_FAILED',
  EXECUTION_TIMEOUT = 'EXECUTION_TIMEOUT',
  NODE_NOT_FOUND = 'NODE_NOT_FOUND',
  EXECUTOR_NOT_REGISTERED = 'EXECUTOR_NOT_REGISTERED',
  WORKFLOW_EXECUTION_ABORTED = 'WORKFLOW_EXECUTION_ABORTED',
  INSUFFICIENT_RESOURCES = 'INSUFFICIENT_RESOURCES',
  MEMORY_LIMIT_EXCEEDED = 'MEMORY_LIMIT_EXCEEDED',
  EXECUTION_QUEUE_FULL = 'EXECUTION_QUEUE_FULL',

  // Data/Configuration errors (422)
  MISSING_WORKFLOW_DEFINITION = 'MISSING_WORKFLOW_DEFINITION',
  INVALID_WORKFLOW_FORMAT = 'INVALID_WORKFLOW_FORMAT',
  INVALID_CONTEXT = 'INVALID_CONTEXT',
  INVALID_PARAMETER = 'INVALID_PARAMETER',
  MISSING_VARIABLE = 'MISSING_VARIABLE',
  INVALID_EXPRESSION = 'INVALID_EXPRESSION',

  // Access control errors (403)
  FORBIDDEN = 'FORBIDDEN',
  TENANT_MISMATCH = 'TENANT_MISMATCH',
  UNAUTHORIZED = 'UNAUTHORIZED',
  PERMISSION_DENIED = 'PERMISSION_DENIED',

  // Not found errors (404)
  NOT_FOUND = 'NOT_FOUND',
  WORKFLOW_NOT_FOUND = 'WORKFLOW_NOT_FOUND',
  EXECUTION_NOT_FOUND = 'EXECUTION_NOT_FOUND',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',

  // Rate limiting (429)
  RATE_LIMITED = 'RATE_LIMITED',
  CONCURRENT_EXECUTION_LIMIT = 'CONCURRENT_EXECUTION_LIMIT',

  // Unknown/Generic errors (500)
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}
