/**
 * useTranslationEditor
 *
 * Powers the Settings → Language tab. Manages:
 * - Locale selection dropdown
 * - Filterable list of all translation keys
 * - Inline editing (via useTranslationEditCRUD)
 * - Row derivation (via useTranslationRows)
 * - Visual "Custom" badge for overridden keys
 *
 * translationListContent is generated by
 * useTranslationListRenderer since JSON definitions
 * can't express render functions.
 */

import {
  useState,
  useCallback,
  useMemo,
  useEffect,
} from 'react'
import { useAppSelector, useAppDispatch } from '@/store'
import {
  setLocale as setLocaleAction,
  fetchTranslations,
} from '@/store/slices/translationsSlice'
import {
  supportedLocales,
  localeNames,
} from '@metabuilder/translations'
import { useTranslationListRenderer } from './use-translation-list-renderer'
import { useTranslationRows } from './use-translation-rows'
import { useTranslationEditCRUD } from './use-translation-edit-crud'

export interface TranslationRow {
  key: string
  staticValue: string
  currentValue: string
  isOverridden: boolean
}

export function useTranslationEditor() {
  const dispatch = useAppDispatch()
  const locale = useAppSelector(
    (state) => state.translations.locale
  )
  const overrides = useAppSelector(
    (state) => state.translations.overrides
  )
  const translationStatus = useAppSelector(
    (state) => state.translations.status
  )

  const [filterQuery, setFilterQuery] = useState('')

  useEffect(() => {
    dispatch(fetchTranslations(locale))
  }, [dispatch, locale])

  const {
    rows,
    staticTranslations,
    overrideCount,
  } = useTranslationRows(filterQuery)

  const {
    editingKey,
    editValue,
    handleEdit,
    handleEditValueChange,
    handleSave,
    handleCancel,
    handleDelete,
  } = useTranslationEditCRUD({
    locale,
    overrides,
    staticTranslations,
  })

  const localeOptions = useMemo(
    () =>
      supportedLocales.map((code) => ({
        value: code,
        label: `${localeNames[code]} (${code})`,
      })),
    []
  )

  const handleLocaleChange = useCallback(
    (
      valueOrEvent:
        | string
        | { target: { value: string } }
    ) => {
      const newLocale =
        typeof valueOrEvent === 'string'
          ? valueOrEvent
          : valueOrEvent.target.value
      dispatch(setLocaleAction(newLocale))
    },
    [dispatch]
  )

  const handleFilterChange = useCallback(
    (
      valueOrEvent:
        | string
        | { target: { value: string } }
    ) => {
      const value =
        typeof valueOrEvent === 'string'
          ? valueOrEvent
          : valueOrEvent.target.value
      setFilterQuery(value)
    },
    []
  )

  const { translationListContent } =
    useTranslationListRenderer({
      rows,
      editingKey,
      editValue,
      onEdit: handleEdit,
      onEditValueChange: handleEditValueChange,
      onSave: handleSave,
      onCancel: handleCancel,
      onDelete: handleDelete,
    })

  return {
    locale,
    localeOptions,
    localeName:
      localeNames[
        locale as keyof typeof localeNames
      ] || locale,
    handleLocaleChange,
    filterQuery,
    handleFilterChange,
    rows,
    totalKeys: staticTranslations.length,
    overrideCount,
    filteredCount: rows.length,
    isLoading: translationStatus === 'loading',
    showEmpty:
      rows.length === 0 && filterQuery.length > 0,
    showRows: rows.length > 0,
    translationListContent,
    editingKey,
    editValue,
    handleEdit,
    handleEditValueChange,
    handleSave,
    handleCancel,
    handleDelete,
  }
}
