entity: InstalledPackage
version: "1.0"
description: "Installed package metadata"

fields:
  packageId:
    type: string
    primary: true
    description: "Package identifier"

  tenantId:
    type: uuid
    optional: true
    nullable: true

  installedAt:
    type: bigint
    required: true

  version:
    type: string
    required: true
    description: "Semantic version"

  enabled:
    type: boolean
    required: true

  config:
    type: string
    optional: true
    nullable: true
    description: "JSON package configuration"

indexes:
  - fields: [tenantId]

acl:
  create:
    role: [supergod]
  read:
    role: [god, supergod]
  update:
    role: [supergod]
  delete:
    role: [supergod]
