/**
 * tabInfo — tab title, icon, and description data map.
 */
import { TabInfo, icons } from './navigation-tab-info-a'
const { ChartBar, Code, Database, Tree, FlowArrow,
  PaintBrush, Flask, Play, BookOpen, Cube, Wrench,
  FileText, Gear, DeviceMobile, Image, Faders,
  Lightbulb, PencilRuler, Atom } = icons
const sz = { size: 24, weight: 'duotone' } as const
const mk = (I: React.ElementType) =>
  <I {...sz} /> as React.ReactNode

export const tabInfo: Record<string, TabInfo> = {
  dashboard: { title: 'Dashboard', icon: mk(ChartBar),
    description: 'Project overview and statistics' },
  code: { title: 'Code Editor', icon: mk(Code),
    description: 'Edit project files' },
  models: { title: 'Models', icon: mk(Database),
    description: 'Define data models' },
  components: { title: 'Components', icon: mk(Tree),
    description: 'Create React components' },
  'component-trees': { title: 'Component Trees',
    icon: mk(Tree),
    description: 'Manage component hierarchies' },
  workflows: { title: 'Workflows', icon: mk(FlowArrow),
    description: 'Design automation workflows' },
  lambdas: { title: 'Lambdas', icon: mk(Code),
    description: 'Serverless functions' },
  styling: { title: 'Styling', icon: mk(PaintBrush),
    description: 'Theme and design tokens' },
  sass: { title: 'Sass Styles', icon: mk(PaintBrush),
    description: 'Custom Sass stylesheets' },
  favicon: { title: 'Favicon Designer', icon: mk(Image),
    description: 'Design app icons' },
  flask: { title: 'Flask API', icon: mk(Flask),
    description: 'Backend API configuration' },
  playwright: { title: 'Playwright', icon: mk(Play),
    description: 'E2E test scenarios' },
  storybook: { title: 'Storybook', icon: mk(BookOpen),
    description: 'Component documentation' },
  'unit-tests': { title: 'Unit Tests', icon: mk(Cube),
    description: 'Unit test suites' },
  errors: { title: 'Error Repair', icon: mk(Wrench),
    description: 'Automated error detection and fixing' },
  docs: { title: 'Documentation', icon: mk(FileText),
    description: 'Project guides and references' },
  settings: { title: 'Settings', icon: mk(Gear),
    description: 'Project configuration' },
  pwa: { title: 'PWA', icon: mk(DeviceMobile),
    description: 'Progressive Web App settings' },
  features: { title: 'Features', icon: mk(Faders),
    description: 'Toggle feature modules' },
  ideas: { title: 'Feature Ideas', icon: mk(Lightbulb),
    description: 'Brainstorm and organize feature ideas' },
  'schema-editor': { title: 'Schema Editor',
    icon: mk(PencilRuler),
    description: 'Visual JSON schema builder' },
  'json-ui': { title: 'JSON UI Showcase', icon: mk(Code),
    description: 'JSON-driven UI examples' },
  'json-conversion-showcase': {
    title: 'JSON Conversion Showcase',
    icon: mk(BookOpen),
    description: 'JSON conversion showcase overview' },
  'atomic-library': { title: 'Atomic Components',
    icon: mk(Atom),
    description: 'Comprehensive atomic component library' },
}
