import { buildScaleClasses, uniqueClasses } from './css-class-utils'

const spacingScale = ['0', '0.5', '1', '1.5', '2', '3', '4', '5', '6', '8', '10', '12', '16']
const sizeScale = ['0', '1', '2', '3', '4', '5', '6', '8', '10', '12', '16', '20', '24', '32', '40', '48', '56', '64']

export const buildSpacingClasses = () =>
  uniqueClasses([
    ...buildScaleClasses(
      ['p', 'px', 'py', 'pt', 'pr', 'pb', 'pl', 'm', 'mx', 'my', 'mt', 'mr', 'mb', 'ml'],
      spacingScale
    ),
    ...buildScaleClasses(['gap', 'gap-x', 'gap-y'], ['0', '1', '2', '3', '4', '6', '8', '10', '12', '16']),
    ...buildScaleClasses(['space-x', 'space-y'], ['0', '1', '2', '3', '4', '6', '8', '10', '12', '16']),
  ])

export const buildSizingClasses = () =>
  uniqueClasses([
    ...buildScaleClasses(['w', 'h'], sizeScale),
    'w-auto',
    'w-full',
    'w-screen',
    'w-min',
    'w-max',
    'w-fit',
    'h-auto',
    'h-full',
    'h-screen',
    'h-min',
    'h-max',
    'h-fit',
    'min-w-0',
    'min-w-full',
    'min-w-min',
    'min-w-max',
    'min-w-fit',
    'min-h-0',
    'min-h-full',
    'min-h-screen',
    'min-h-min',
    'min-h-max',
    'min-h-fit',
    'max-w-none',
    'max-w-xs',
    'max-w-sm',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'max-w-2xl',
    'max-w-3xl',
    'max-w-4xl',
    'max-w-5xl',
    'max-w-6xl',
    'max-w-7xl',
    'max-w-full',
    'max-w-screen-sm',
    'max-w-screen-md',
    'max-w-screen-lg',
    'max-w-screen-xl',
    'max-h-none',
    'max-h-full',
    'max-h-screen',
    'w-1/2',
    'w-1/3',
    'w-2/3',
    'w-1/4',
    'w-2/4',
    'w-3/4',
    'w-1/5',
    'w-2/5',
    'w-3/5',
    'w-4/5',
    'w-1/6',
    'w-2/6',
    'w-3/6',
    'w-4/6',
    'w-5/6',
    'h-1/2',
    'h-1/3',
    'h-2/3',
    'h-1/4',
    'h-2/4',
    'h-3/4',
    'h-1/5',
    'h-2/5',
    'h-3/5',
    'h-4/5',
  ])
