export { Tabs } from '../tabs/core/Tabs'
export type { TabsProps } from '../tabs/core/Tabs'
export { TabsList } from '../tabs/components/TabsList'
export type { TabsListProps } from '../tabs/components/TabsList'
export { TabsTrigger } from '../tabs/components/TabsTrigger'
export type { TabsTriggerProps } from '../tabs/components/TabsTrigger'
export { TabsContent } from '../tabs/components/TabsContent'
export type { TabsContentProps } from '../tabs/components/TabsContent'
