export { Tabs } from './tabs/Tabs'
export type { TabsProps } from './tabs/Tabs'
export { TabsList } from './tabs/TabsList'
export type { TabsListProps } from './tabs/TabsList'
export { TabsTrigger } from './tabs/TabsTrigger'
export type { TabsTriggerProps } from './tabs/TabsTrigger'
export { TabsContent } from './tabs/TabsContent'
export type { TabsContentProps } from './tabs/TabsContent'
