var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__553e8c63._.js")
R.c("server/chunks/ssr/frontends_dockerterminal_frontend_98a1ced8._.js")
R.c("server/chunks/ssr/frontends_dockerterminal_frontend_47f129fc._.js")
R.c("server/chunks/ssr/[root-of-the-server]__d22c6dd6._.js")
R.c("server/chunks/ssr/[root-of-the-server]__91d9c139._.js")
R.c("server/chunks/ssr/_6489d8a7._.js")
R.c("server/chunks/ssr/frontends_dockerterminal_frontend_app_555d16b2._.js")
R.c("server/chunks/ssr/7851d_next_dist_client_components_builtin_global-error_91ee9f48.js")
R.c("server/chunks/ssr/frontends_dockerterminal_frontend_a865885c._.js")
R.c("server/chunks/ssr/7851d_next_dist_client_components_5c7fc595._.js")
R.c("server/chunks/ssr/7851d_next_dist_client_components_builtin_forbidden_7bdb795f.js")
R.c("server/chunks/ssr/7851d_next_dist_client_components_builtin_unauthorized_ac0c6f1d.js")
R.c("server/chunks/ssr/88fd4_dockerterminal_frontend__next-internal_server_app_page_actions_077dae05.js")
R.m(8091)
module.exports=R.m(8091).exports
